version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: nicolaspj
      MYSQL_DATABASE: peliculas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  moviesnest-app:
    image: nicolasp58/moviesnest:latest  # Usar imagen de Docker Hub
    container_name: moviesnest-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/peliculas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nicolaspj
      CURRENCY_API_KEY: 3685a842ed0b5dce0bef01b8
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge